### ISSUE TITLE
Language selector is missing an entry for "zh_TW" (正體中文)

### ISSUE THREAD

**Issue by andy0130tw** [FraxFinance/frax-langs#39]
I have contributed the localization of zh_TW as a PR and it has been merged. However, in the trading app, the language selector did not account of the addition of this new language, making it unusable on the app. I propose adding an entry of label "正體中文", along with a flag with country code `TW` should be appropriate (assuming using [ekwonye-richard/react-flags-select](https://github.com/ekwonye-richard/react-flags-select)). Thanks in advance!

FYI:  
![2021-10-02 04-29-07](https://user-images.githubusercontent.com/5269414/135682695-a14b397c-dbbd-461e-8b80-3f1878e00f3c.png)

**Comment by FortisFortuna** [comment]
Will add.

**Comment by FortisFortuna** [comment]
Moved to https://github.com/FraxFinance/frax-langs/tree/master/tw

**Comment by andy0130tw** [comment]
@FortisFortuna I have seen the language selector updated, and it works as intended. Thanks for your prompt support!
